global:
  scrape_interval: 5s
  external_labels:
    nats: 'nats-server'
    fastify: 'fastify-api'
    postgres: 'postgresql-db'

scrape_configs:
  - job_name: 'nats-server'
    static_configs:
      - targets: ['nats-exporter:7777']
  - job_name: 'fastify-api'
    static_configs:
      - targets: ['host.docker.internal:3001']
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgresql-exporter:9187']