# Define network
networks:
  DbNetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24

# Define volumes
volumes:
  postgres_data:
    driver: local

# Define services
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} # Change to desired DB name in env file
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      DbNetwork:
        ipv4_address: 172.20.0.2

    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    networks:
      - DbNetwork
    ports:
      - "5050:80"
    restart: always
