networks:
  DbNetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} # Change to desired DB name in env file
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      DbNetwork:
        ipv4_address: 172.20.0.2

    restart: always

  redis:
    container_name: redis
    image: redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PW}
    command: redis-server --requirepass ${REDIS_PW}
    ports:
      - "6379:6379"
    networks:
      DbNetwork:
        ipv4_address: 172.20.0.3

    restart: always
