# Define network
networks:
  DbNetwork:
    driver: bridge

# Define volumes
volumes:
  postgres_data:
    driver: local

# Define services
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} # Change to desired DB name in env file
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - DbNetwork

    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    networks:
      - DbNetwork
    ports:
      - "5050:80"
    restart: always
