networks:
  DbNetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24

volumes:
  postgres_data:
    driver: local
  nats_data:
    driver: local
  grafana_data:
    driver: local

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} # Change to desired DB name in env file
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      DbNetwork:
        ipv4_address: 172.20.0.2

    restart: always

  redis:
    container_name: redis
    image: redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PW}
    command: redis-server --requirepass ${REDIS_PW}
    ports:
      - "6379:6379"
    networks:
      DbNetwork:
        ipv4_address: 172.20.0.3

    restart: always

  nats:
    container_name: nats
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222" # DO NOT EXPOSE THIS PORT FOR PRODUCTION DEPLOYMENTS
    networks:
      DbNetwork:
        ipv4_address: 172.20.0.4
    volumes:
      - nats_data:/var/lib/nats
    command: >
      -js -sd /var/lib/nats -m 8222 -a 0.0.0.0

    restart: always

  nats-exporter:
    image: natsio/prometheus-nats-exporter:latest
    container_name: nats-exporter
    ports:
      - "7777:7777"
    networks:
      DbNetwork:
        ipv4_address: 172.20.0.5
    depends_on:
      - nats
    command: "-connz -subz -varz -jsz=all -healthz -connz http://nats:8222"

    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      DbNetwork:
        ipv4_address: 172.20.0.6

    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - nats-exporter
    networks:
      DbNetwork:
        ipv4_address: 172.20.0.7

    volumes:
      - grafana_data:/var/lib/grafana

    restart: always
